{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-GB",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/ ;AdventureWorksDW2022",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": ".",
            "database": "AdventureWorksDW2022"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductAlternateKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternateKey"
          },
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "WeightUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "WeightUnitMeasureCode"
          },
          {
            "name": "SizeUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "SizeUnitMeasureCode"
          },
          {
            "name": "EnglishProductName",
            "dataType": "string",
            "sourceColumn": "EnglishProductName"
          },
          {
            "name": "SpanishProductName",
            "dataType": "string",
            "sourceColumn": "SpanishProductName"
          },
          {
            "name": "FrenchProductName",
            "dataType": "string",
            "sourceColumn": "FrenchProductName"
          },
          {
            "name": "StandardCost",
            "dataType": "decimal",
            "sourceColumn": "StandardCost"
          },
          {
            "name": "FinishedGoodsFlag",
            "dataType": "boolean",
            "sourceColumn": "FinishedGoodsFlag"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "SafetyStockLevel",
            "dataType": "int64",
            "sourceColumn": "SafetyStockLevel"
          },
          {
            "name": "ReorderPoint",
            "dataType": "int64",
            "sourceColumn": "ReorderPoint"
          },
          {
            "name": "ListPrice",
            "dataType": "decimal",
            "sourceColumn": "ListPrice"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size"
          },
          {
            "name": "SizeRange",
            "dataType": "string",
            "sourceColumn": "SizeRange"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight"
          },
          {
            "name": "DaysToManufacture",
            "dataType": "int64",
            "sourceColumn": "DaysToManufacture"
          },
          {
            "name": "ProductLine",
            "dataType": "string",
            "sourceColumn": "ProductLine"
          },
          {
            "name": "DealerPrice",
            "dataType": "decimal",
            "sourceColumn": "DealerPrice"
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class"
          },
          {
            "name": "Style",
            "dataType": "string",
            "sourceColumn": "Style"
          },
          {
            "name": "ModelName",
            "dataType": "string",
            "sourceColumn": "ModelName"
          },
          {
            "name": "EnglishDescription",
            "dataType": "string",
            "sourceColumn": "EnglishDescription"
          },
          {
            "name": "FrenchDescription",
            "dataType": "string",
            "sourceColumn": "FrenchDescription"
          },
          {
            "name": "ChineseDescription",
            "dataType": "string",
            "sourceColumn": "ChineseDescription"
          },
          {
            "name": "ArabicDescription",
            "dataType": "string",
            "sourceColumn": "ArabicDescription"
          },
          {
            "name": "HebrewDescription",
            "dataType": "string",
            "sourceColumn": "HebrewDescription"
          },
          {
            "name": "ThaiDescription",
            "dataType": "string",
            "sourceColumn": "ThaiDescription"
          },
          {
            "name": "GermanDescription",
            "dataType": "string",
            "sourceColumn": "GermanDescription"
          },
          {
            "name": "JapaneseDescription",
            "dataType": "string",
            "sourceColumn": "JapaneseDescription"
          },
          {
            "name": "TurkishDescription",
            "dataType": "string",
            "sourceColumn": "TurkishDescription"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "type": "calculated",
            "name": "SubCategory Name",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED(DimProductSubcategory[EnglishProductSubcategoryName])"
          },
          {
            "type": "calculated",
            "name": "Category Name",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED(DimProductCategory[EnglishProductCategoryName])"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;AdventureWorksDW2022\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data]",
                "in",
                "    dbo_DimProduct"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Product Category",
            "levels": [
              {
                "name": "SubCategory Name",
                "ordinal": 1,
                "column": "SubCategory Name"
              },
              {
                "name": "Category Name",
                "ordinal": 0,
                "column": "Category Name"
              },
              {
                "name": "EnglishProductName",
                "ordinal": 2,
                "column": "EnglishProductName"
              }
            ]
          }
        ]
      },
      {
        "name": "DimProductCategory",
        "columns": [
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          },
          {
            "name": "ProductCategoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryAlternateKey"
          },
          {
            "name": "EnglishProductCategoryName",
            "dataType": "string",
            "sourceColumn": "EnglishProductCategoryName"
          },
          {
            "name": "SpanishProductCategoryName",
            "dataType": "string",
            "sourceColumn": "SpanishProductCategoryName"
          },
          {
            "name": "FrenchProductCategoryName",
            "dataType": "string",
            "sourceColumn": "FrenchProductCategoryName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;AdventureWorksDW2022\",",
                "    dbo_DimProductCategory = Source{[Schema=\"dbo\",Item=\"DimProductCategory\"]}[Data]",
                "in",
                "    dbo_DimProductCategory"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProductSubcategory",
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "ProductSubcategoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryAlternateKey"
          },
          {
            "name": "EnglishProductSubcategoryName",
            "dataType": "string",
            "sourceColumn": "EnglishProductSubcategoryName"
          },
          {
            "name": "SpanishProductSubcategoryName",
            "dataType": "string",
            "sourceColumn": "SpanishProductSubcategoryName"
          },
          {
            "name": "FrenchProductSubcategoryName",
            "dataType": "string",
            "sourceColumn": "FrenchProductSubcategoryName"
          },
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;AdventureWorksDW2022\",",
                "    dbo_DimProductSubcategory = Source{[Schema=\"dbo\",Item=\"DimProductSubcategory\"]}[Data]",
                "in",
                "    dbo_DimProductSubcategory"
              ]
            }
          }
        ]
      },
      {
        "name": "DimEmployee",
        "columns": [
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "ParentEmployeeKey",
            "dataType": "int64",
            "sourceColumn": "ParentEmployeeKey"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "type": "calculated",
            "name": "FullName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "DimEmployee[FirstName] & \" \" &DimEmployee[LastName]"
          },
          {
            "type": "calculated",
            "name": "Employee Path",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "PATH(DimEmployee[EmployeeKey],DimEmployee[ParentEmployeeKey])"
          },
          {
            "type": "calculated",
            "name": "Employee Path Length",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "PATHLENGTH(DimEmployee[Employee Path])"
          },
          {
            "type": "calculated",
            "name": "Path item employee",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "PATHITEM(DimEmployee[Employee Path],1,INTEGER)"
          },
          {
            "type": "calculated",
            "name": "PathItemReverse Employee",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "PATHITEMREVERSE(DimEmployee[Employee Path],3,INTEGER)"
          },
          {
            "type": "calculated",
            "name": "Level1 Name",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE(DimEmployee[FullName],DimEmployee[EmployeeKey],DimEmployee[Path item employee])"
          },
          {
            "type": "calculated",
            "name": "level 2 Name",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE(DimEmployee[FullName],DimEmployee[EmployeeKey],PATHITEM(DimEmployee[Employee Path],2,INTEGER))"
          },
          {
            "type": "calculated",
            "name": "Level3 Name",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE(DimEmployee[FullName],DimEmployee[EmployeeKey],PATHITEM(DimEmployee[Employee Path],3,INTEGER))"
          },
          {
            "type": "calculated",
            "name": "Level4 Name",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE(DimEmployee[FullName],DimEmployee[EmployeeKey],PATHITEM(DimEmployee[Employee Path],4,INTEGER))"
          },
          {
            "type": "calculated",
            "name": "Level 5 Name",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE(DimEmployee[FullName],DimEmployee[EmployeeKey],PATHITEM(DimEmployee[Employee Path],5,INTEGER))"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;AdventureWorksDW2022\",",
                "    dbo_DimEmployee = Source{[Schema=\"dbo\",Item=\"DimEmployee\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_DimEmployee,{\"EmployeeKey\", \"ParentEmployeeKey\", \"FirstName\", \"LastName\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Employee Path Length Max",
            "expression": "MAX(DimEmployee[Employee Path Length])"
          }
        ],
        "hierarchies": [
          {
            "name": "Employee H",
            "levels": [
              {
                "name": "Level1 Name",
                "ordinal": 0,
                "column": "Level1 Name"
              },
              {
                "name": "level 2 Name",
                "ordinal": 1,
                "column": "level 2 Name"
              },
              {
                "name": "Level3 Name",
                "ordinal": 2,
                "column": "Level3 Name"
              },
              {
                "name": "Level4 Name",
                "ordinal": 3,
                "column": "Level4 Name"
              },
              {
                "name": "Level 5 Name",
                "ordinal": 4,
                "column": "Level 5 Name"
              }
            ]
          }
        ]
      },
      {
        "name": "FactResellerSales",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "DueDateKey",
            "dataType": "int64",
            "sourceColumn": "DueDateKey"
          },
          {
            "name": "ShipDateKey",
            "dataType": "int64",
            "sourceColumn": "ShipDateKey"
          },
          {
            "name": "ResellerKey",
            "dataType": "int64",
            "sourceColumn": "ResellerKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "sourceColumn": "CurrencyKey"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "RevisionNumber",
            "dataType": "int64",
            "sourceColumn": "RevisionNumber"
          },
          {
            "name": "OrderQuantity",
            "dataType": "int64",
            "sourceColumn": "OrderQuantity"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "ExtendedAmount",
            "dataType": "decimal",
            "sourceColumn": "ExtendedAmount"
          },
          {
            "name": "UnitPriceDiscountPct",
            "dataType": "double",
            "sourceColumn": "UnitPriceDiscountPct"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount"
          },
          {
            "name": "ProductStandardCost",
            "dataType": "decimal",
            "sourceColumn": "ProductStandardCost"
          },
          {
            "name": "TotalProductCost",
            "dataType": "decimal",
            "sourceColumn": "TotalProductCost"
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount"
          },
          {
            "name": "TaxAmt",
            "dataType": "decimal",
            "sourceColumn": "TaxAmt"
          },
          {
            "name": "Freight",
            "dataType": "decimal",
            "sourceColumn": "Freight"
          },
          {
            "name": "CarrierTrackingNumber",
            "dataType": "string",
            "sourceColumn": "CarrierTrackingNumber"
          },
          {
            "name": "CustomerPONumber",
            "dataType": "string",
            "sourceColumn": "CustomerPONumber"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate"
          },
          {
            "name": "DueDate",
            "dataType": "dateTime",
            "sourceColumn": "DueDate"
          },
          {
            "name": "ShipDate",
            "dataType": "dateTime",
            "sourceColumn": "ShipDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;AdventureWorksDW2022\",",
                "    dbo_FactResellerSales = Source{[Schema=\"dbo\",Item=\"FactResellerSales\"]}[Data]",
                "in",
                "    dbo_FactResellerSales"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "b00c52e0-1e54-4ab5-8ced-614835dbe964",
        "fromTable": "DimProduct",
        "fromColumn": "ProductSubcategoryKey",
        "toTable": "DimProductSubcategory",
        "toColumn": "ProductSubcategoryKey"
      },
      {
        "name": "5f06f540-7bfb-4036-9a43-164f2c2f3fa1",
        "fromTable": "FactResellerSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "1827d8cd-64a5-4ab7-b0ef-d401e2cc1458",
        "fromTable": "DimProductSubcategory",
        "fromColumn": "ProductCategoryKey",
        "toTable": "DimProductCategory",
        "toColumn": "ProductCategoryKey"
      },
      {
        "name": "0a570f42-9d80-47bf-a94f-c018703dff70",
        "fromTable": "FactResellerSales",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}