EVALUATE
'Date'


EVALUATE
{
count('Date'[Date])
}

EVALUATE
{
COUNTROWS('Date')
}

EVALUATE
{
COUNTBLANK(Store[Status])
}


EVALUATE
{
Count(Store[Status])
}

EVALUATE
{
COUNTROWS(Store)
}


EVALUATE
VALUES(
Store[Status])

EVALUATE
{
DISTINCTCOUNT(
Store[Status])
}


EVALUATE
{
DISTINCTCOUNTNOBLANK(
Store[Status])
}