Define

VAR _customer=SELECTCOLUMNS(VALUES(Customer[Country]),"Country",[Country] & "","@Customer",CALCULATE(COUNTROWS(Customer)))
VAR _store=SELECTCOLUMNS(VALUES(Store[Country]),"Country",[Country] & "","@Store",CALCULATE(COUNTROWS(Store)))




EVALUATE
_customer

EVALUATE
_store

EVALUATE
NATURALINNERJOIN(_customer,_store)

EVALUATE
NATURALLEFTOUTERJOIN(_customer,_store)


EVALUATE
NATURALLEFTOUTERJOIN(_store,_customer)