{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-GB",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/ ;Contoso",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": ".",
            "database": "Contoso"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": ".;Contoso",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Store",
        "columns": [
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "name": "Open Date",
            "dataType": "dateTime",
            "sourceColumn": "Open Date"
          },
          {
            "name": "Close Date",
            "dataType": "dateTime",
            "sourceColumn": "Close Date"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;Contoso\",",
                "    dbo_Store = Source{[Schema=\"dbo\",Item=\"Store\"]}[Data]",
                "in",
                "    dbo_Store"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales",
        "columns": [
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "Order Date",
            "encodingHint": "value"
          },
          {
            "name": "Delivery Date",
            "dataType": "dateTime",
            "sourceColumn": "Delivery Date"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey"
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "Currency Code"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity"
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price"
          },
          {
            "name": "Net Price",
            "dataType": "decimal",
            "sourceColumn": "Net Price"
          }
        ],
        "partitions": [
          {
            "name": "Partition2010",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;Contoso\",",
                "    Contoso = Source{[Name=\"Contoso\"]}[Data],",
                "    dbo_Sales = Contoso{[Schema=\"dbo\",Item=\"Sales\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_Sales, each [Order Date] >= #date(2010, 1, 1) and [Order Date] < #date(2011, 1, 1))",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/ ;Contoso\",",
                  "    Contoso = Source{[Name=\"Contoso\"]}[Data],",
                  "    dbo_Sales = Contoso{[Schema=\"dbo\",Item=\"Sales\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_Sales, each [Order Date] >= #date(2010, 1, 1) and [Order Date] < #date(2011, 1, 1))",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Partition2011",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;Contoso\",",
                "    Contoso = Source{[Name=\"Contoso\"]}[Data],",
                "    dbo_Sales = Contoso{[Schema=\"dbo\",Item=\"Sales\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_Sales, each [Order Date] >= #date(2011, 1, 1) and [Order Date] < #date(2012, 1, 1))",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/ ;Contoso\",",
                  "    Contoso = Source{[Name=\"Contoso\"]}[Data],",
                  "    dbo_Sales = Contoso{[Schema=\"dbo\",Item=\"Sales\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_Sales, each [Order Date] >= #date(2011, 1, 1) and [Order Date] < #date(2012, 1, 1))",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Partition2013",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;Contoso\",",
                "    Contoso = Source{[Name=\"Contoso\"]}[Data],",
                "    dbo_Sales = Contoso{[Schema=\"dbo\",Item=\"Sales\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_Sales, each [Order Date] >= #date(2012, 1, 1) and [Order Date] < #date(2013, 1, 1))",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/ ;Contoso\",",
                  "    Contoso = Source{[Name=\"Contoso\"]}[Data],",
                  "    dbo_Sales = Contoso{[Schema=\"dbo\",Item=\"Sales\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_Sales, each [Order Date] >= #date(2012, 1, 1) and [Order Date] < #date(2013, 1, 1))",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales Amount",
            "expression": "SUMX(Sales,Sales[Quantity]*Sales[Unit Price])",
            "detailRowsDefinition": {
              "expression": "SELECTCOLUMNS(Sales,\"Product Name\",RELATED('Product'[Product Name]),\"Customer Name\",RELATED(Customer[Name]),\"Sales Amount\",[Sales Amount])"
            }
          },
          {
            "name": "Sales Quantity",
            "expression": "SUM(Sales[Quantity])"
          }
        ]
      },
      {
        "name": "Product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost"
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price"
          },
          {
            "name": "Subcategory",
            "dataType": "string",
            "sourceColumn": "Subcategory"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;Contoso\",",
                "    dbo_Product = Source{[Schema=\"dbo\",Item=\"Product\"]}[Data]",
                "in",
                "    dbo_Product"
              ]
            }
          }
        ]
      },
      {
        "name": "Date",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Year Month",
            "dataType": "string",
            "sourceColumn": "Year Month"
          },
          {
            "name": "Year Month Number",
            "dataType": "int64",
            "sourceColumn": "Year Month Number"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "Month Number"
          },
          {
            "name": "Day of Week",
            "dataType": "string",
            "sourceColumn": "Day of Week"
          },
          {
            "name": "Day of Week Number",
            "dataType": "int64",
            "sourceColumn": "Day of Week Number"
          },
          {
            "name": "Working Day",
            "dataType": "boolean",
            "sourceColumn": "Working Day"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;Contoso\",",
                "    dbo_Date = Source{[Schema=\"dbo\",Item=\"Date\"]}[Data]",
                "in",
                "    dbo_Date"
              ]
            }
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "encodingHint": "value"
          },
          {
            "name": "Country Code",
            "dataType": "string",
            "sourceColumn": "Country Code"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent"
          },
          {
            "name": "Age",
            "dataType": "int64",
            "sourceColumn": "Age"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;Contoso\",",
                "    dbo_Customer = Source{[Schema=\"dbo\",Item=\"Customer\"]}[Data]",
                "in",
                "    dbo_Customer"
              ]
            }
          }
        ]
      },
      {
        "name": "Time Intelligence",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Measure",
              "expression": "SELECTEDMEASURE()"
            },
            {
              "name": "MTD",
              "expression": "TOTALMTD(SELECTEDMEASURE(),'Date'[Date])"
            },
            {
              "name": "YTD",
              "expression": "TOTALYTD(SELECTEDMEASURE(),'Date'[Date])"
            }
          ]
        },
        "columns": [
          {
            "name": "ToDate",
            "dataType": "string",
            "sourceColumn": "Name"
          }
        ],
        "partitions": [
          {
            "name": "CalculationGroup 1",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Sales 1",
        "columns": [
          {
            "name": "Delivery Date",
            "dataType": "dateTime",
            "sourceColumn": "Delivery Date"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey"
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "Currency Code"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity"
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price"
          },
          {
            "name": "Net Price",
            "dataType": "decimal",
            "sourceColumn": "Net Price"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;Contoso\",",
                "    dbo_Sales = Source{[Schema=\"dbo\",Item=\"Sales\"]}[Data]",
                "in",
                "    dbo_Sales"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "26200852-755f-453f-bc10-8dffb0ca64cf",
        "fromTable": "Sales",
        "fromColumn": "ProductKey",
        "toTable": "Product",
        "toColumn": "ProductKey"
      },
      {
        "name": "d463a43c-a903-4f3b-b48c-506fb8668589",
        "fromTable": "Sales",
        "fromColumn": "StoreKey",
        "toTable": "Store",
        "toColumn": "StoreKey"
      },
      {
        "name": "ed022600-b686-4906-a0c7-e76f9c0570db",
        "fromTable": "Sales",
        "fromColumn": "Order Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "60a42d12-4964-4206-96f2-6e211b9f4cf4",
        "fromTable": "Sales",
        "fromColumn": "CustomerKey",
        "toTable": "Customer",
        "toColumn": "CustomerKey"
      }
    ],
    "cultures": [
      {
        "name": "en-GB",
        "translations": {
          "model": {
            "name": "Model",
            "translatedCaption": "مدل",
            "tables": [
              {
                "name": "Store",
                "translatedCaption": "فروشگاه",
                "columns": [
                  {
                    "name": "Name",
                    "translatedCaption": "نام فروشگاه"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "Sales",
        "tables": [
          {
            "name": "Customer",
            "columns": [
              {
                "name": "Age"
              },
              {
                "name": "City"
              },
              {
                "name": "Continent"
              },
              {
                "name": "Country"
              },
              {
                "name": "Country Code"
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Name"
              },
              {
                "name": "State"
              }
            ]
          },
          {
            "name": "Sales",
            "columns": [
              {
                "name": "Currency Code"
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "Delivery Date"
              },
              {
                "name": "Net Price"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "StoreKey"
              },
              {
                "name": "Unit Price"
              }
            ],
            "measures": [
              {
                "name": "Sales Amount"
              }
            ]
          }
        ]
      },
      {
        "name": "MArketing",
        "tables": [
          {
            "name": "Date",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "Day of Week"
              },
              {
                "name": "Day of Week Number"
              },
              {
                "name": "Month"
              },
              {
                "name": "Month Number"
              },
              {
                "name": "Year Month"
              },
              {
                "name": "Year Month Number"
              }
            ]
          },
          {
            "name": "Product",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Category"
              },
              {
                "name": "Color"
              },
              {
                "name": "Product Name"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "Subcategory"
              },
              {
                "name": "Unit Cost"
              },
              {
                "name": "Unit Price"
              }
            ]
          },
          {
            "name": "Sales",
            "columns": [
              {
                "name": "Currency Code"
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "Delivery Date"
              },
              {
                "name": "Net Price"
              },
              {
                "name": "Order Date"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "StoreKey"
              },
              {
                "name": "Unit Price"
              }
            ],
            "measures": [
              {
                "name": "Sales Amount"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Role"
      },
      {
        "name": "Marketing-Canada",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "Farnoosh",
            "memberId": "S-1-5-21-3077242351-2196448990-1428570751-1001"
          }
        ],
        "tablePermissions": [
          {
            "name": "Customer",
            "filterExpression": "Customer[Country]=\"canada\""
          },
          {
            "name": "Sales",
            "columnPermissions": [
              {
                "name": "Delivery Date",
                "metadataPermission": "none"
              }
            ]
          }
        ]
      },
      {
        "name": "Marketing-Customer[Country]",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Customer",
            "filterExpression": "Customer[Country]=\"France\""
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}